[package]
name = "plugin"
edition = "2021"
version.workspace = true
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/scotch"

[target.'cfg(target_arch = "wasm32")'.lib]
crate-type = ["cdylib"]

 [lib]
 crate-type = ["cdylib"]
 
 [dependencies]
scotch-guest = { path = "../../guest" }
common = { path = "../common" }
